import { Language, Translation, LanguageCode } from './types';

export const COURSES = ['BCA', 'BSc CS', 'BTech', 'BCom', 'BBA', 'MCA', 'MSc'];
export const SEMESTERS = [1, 2, 3, 4, 5, 6, 7, 8];

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
];

export const TRANSLATIONS: Translation = {
  appTitle: {
    en: 'EduTrack AI',
    hi: 'एजुट्रैक एआई',
    gu: 'એજ્યુટ્રેક એઆઈ',
    mr: 'एज्युट्रॅक एआय',
    ta: 'எடுட்ராக் AI',
    te: 'ఎడ్యుట్రాక్ AI',
    kn: 'ಎಜುಟ್ರಾಕ್ AI',
    bn: 'এডুট্র্যাক এআই',
    pa: 'ਐਜੂਟ੍ਰੈਕ ਏਆਈ',
    ml: 'എഡ്യുട്രാക്ക് AI',
    or: 'ଏଜୁଟ୍ରାକ୍ AI',
    ur: 'ایجو ٹریک اے آئی',
  },
  login: {
    en: 'Login',
    hi: 'लॉगिन',
    gu: 'લૉગિન',
    mr: 'लॉगिन',
    ta: 'உள்நுழைய',
    te: 'లాగిన్',
    kn: 'ಲಾಗಿನ್',
    bn: 'লগইন',
    pa: 'ਲੌਗਇਨ',
    ml: 'ലോഗിൻ',
    or: 'ଲଗ୍ ଇନ୍',
    ur: 'لاگ ان',
  },
  username: {
    en: 'Username',
    hi: 'उपयोगकर्ता नाम',
    gu: 'વપરાશકર્તા નામ',
    mr: 'वापरकर्तानाव',
    ta: 'பயனர்பெயர்',
    te: 'వినియోగదారు పేరు',
    kn: 'ಬಳಕೆದಾರ ಹೆಸರು',
    bn: 'ব্যবহারকারীর নাম',
    pa: 'ਯੂਜ਼ਰ ਨਾਂ',
    ml: 'ഉപയോക്തൃനാമം',
    or: 'ଉପଭୋକ୍ତା ନାମ',
    ur: 'صارف کا نام',
  },
  password: {
    en: 'Password',
    hi: 'पासवर्ड',
    gu: 'પાસવર્ડ',
    mr: 'पासवर्ड',
    ta: 'கடவுச்சொல்',
    te: 'పాస్‌వర్డ్',
    kn: 'ಪಾಸ್‌ವರ್ಡ್',
    bn: 'পাসওয়ার্ড',
    pa: 'ਪਾਸਵਰਡ',
    ml: 'പാസ്‌വേഡ്',
    or: 'ପାସୱାର୍ଡ',
    ur: 'پاس ورڈ',
  },
  teachers: {
    en: 'Teachers',
    hi: 'शिक्षक',
    gu: 'શિક્ષકો',
    mr: 'शिक्षक',
    ta: 'ஆசிரியர்கள்',
    te: 'ఉపాధ్యాయులు',
    kn: 'ಶಿಕ್ಷಕರು',
    bn: 'শিক্ষক',
    pa: 'ਅਧਿਆਪਕ',
    ml: 'അധ്യാപകർ',
    or: 'ଶିକ୍ଷକମାନେ',
    ur: 'اساتذہ',
  },
  manageTeachers: {
    en: 'Manage Teachers',
    hi: 'शिक्षकों का प्रबंधन',
    gu: 'શિક્ષકોનું સંચાલન',
    mr: 'शिक्षक व्यवस्थापन',
    ta: 'ஆசிரியர்களை நிர்வகி',
    te: 'ఉపాధ్యాయులను నిర్వహించండి',
    kn: 'ಶಿಕ್ಷಕರನ್ನು ನಿರ್ವಹಿಸಿ',
    bn: 'শিক্ষক পরিচালনা',
    pa: 'ਅਧਿਆਪਕ ਪ੍ਰਬੰਧਨ',
    ml: 'അധ്യാപക മാനേജ്മെന്റ്',
    or: 'ଶିକ୍ଷକ ପରିଚାଳନା',
    ur: 'اساتذہ کا انتظام',
  },
  dashboard: {
    en: 'Dashboard',
    hi: 'डैशबोर्ड',
    gu: 'ડેશબોર્ડ',
    mr: 'डॅशबोर्ड',
    ta: 'டாஷ்போர்டு',
    te: 'డాష్‌బోర్డ్',
    kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    bn: 'ড্যাশবোর্ড',
    pa: 'ਡੈਸ਼ਬੋਰਡ',
    ml: 'ഡാഷ്ബോർഡ്',
    or: 'ଡ୍ୟାସବୋର୍ଡ',
    ur: 'ڈیش بورڈ',
  },
  students: {
    en: 'Students',
    hi: 'छात्र',
    gu: 'વિદ્યાર્થીઓ',
    mr: 'विद्यार्थी',
    ta: 'மாணவர்கள்',
    te: 'విద్యార్థులు',
    kn: 'ವಿದ್ಯಾರ್ಥಿಗಳು',
    bn: 'শিক্ষার্থীরা',
    pa: 'ਵਿਦਿਆਰਥੀ',
    ml: 'വിദ്യാർത്ഥികൾ',
    or: 'ଛାତ୍ର',
    ur: 'طلباء',
  },
  attendance: {
    en: 'Attendance',
    hi: 'उपस्थिति',
    gu: 'હાજરી',
    mr: 'उपस्थिती',
    ta: 'வருகை',
    te: 'హాజరు',
    kn: 'ಹಾಜರಾತಿ',
    bn: 'উপস্থিতি',
    pa: 'ਹਾਜ਼ਰੀ',
    ml: 'ഹാജർ',
    or: 'ଉପସ୍ଥାନ',
    ur: 'حاضری',
  },
  performance: {
    en: 'Performance',
    hi: 'प्रदर्शन',
    gu: 'પ્રદર્શન',
    mr: 'कामगिरी',
    ta: 'செயல்திறன்',
    te: 'పనితీరు',
    kn: 'ಕಾರ್ಯಕ್ಷಮತೆ',
    bn: 'কর্মক্ষমতা',
    pa: 'ਪ੍ਰਦਰਸ਼ਨ',
    ml: 'പ്രകടനം',
    or: 'ପ୍ରଦର୍ଶନ',
    ur: 'کارکردگی',
  },
  logout: {
    en: 'Logout',
    hi: 'लॉग आउट',
    gu: 'લોગ આઉટ',
    mr: 'लॉग आउट',
    ta: 'வெளியேறு',
    te: 'లాగ్ అవుట్',
    kn: 'ಲಾಗ್ ಔಟ್',
    bn: 'লগ আউট',
    pa: 'ਲੋਗ ਆਉਟ',
    ml: 'ലോഗ് ഔട്ട്',
    or: 'ଲଗ୍ ଆଉଟ୍',
    ur: 'لاگ آوٹ',
  },
  welcome: {
    en: 'Welcome',
    hi: 'स्वागत है',
    gu: 'સ્વાગત છે',
    mr: 'स्वागत आहे',
    ta: 'வரவேற்பு',
    te: 'స్వాగతం',
    kn: 'ಸ್ವಾಗತ',
    bn: 'স্বাগতম',
    pa: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    ml: 'സ്വാഗതം',
    or: 'ସ୍ୱାଗତ',
    ur: 'خوش آمدید',
  },
  totalStudents: {
    en: 'Total Students',
    hi: 'कुल छात्र',
    gu: 'કુલ વિદ્યાર્થીઓ',
    mr: 'एकूण विद्यार्थी',
    ta: 'மொத்த மாணவர்கள்',
    te: 'మొత్తం విద్యార్థులు',
    kn: 'ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು',
    bn: 'মোট শিক্ষার্থী',
    pa: 'ਕੁੱਲ ਵਿਦਿਆਰਥੀ',
    ml: 'ആകെ വിദ്യാർത്ഥികൾ',
    or: 'ସମୁଦାୟ ଛାତ୍ର',
    ur: 'کل طلباء',
  },
  lowAttendance: {
    en: 'Low Attendance',
    hi: 'कम उपस्थिति',
    gu: 'ઓછી હાજરી',
    mr: 'कमी उपस्थिती',
    ta: 'குறைந்த வருகை',
    te: 'తక్కువ హాజరు',
    kn: 'ಕಡಿಮೆ ಹಾಜರಾತಿ',
    bn: 'কম উপস্থিতি',
    pa: 'ਘੱਟ ਹਾਜ਼ਰੀ',
    ml: 'കുറഞ്ഞ ഹാജർ',
    or: 'କମ ଉପସ୍ଥାନ',
    ur: 'کم حاضری',
  },
  averageScore: {
    en: 'Average Score',
    hi: 'औसत अंक',
    gu: 'સરેરાશ સ્કોર',
    mr: 'सरासरी गुण',
    ta: 'சராசரி மதிப்பெண்',
    te: 'సగటు స్కోరు',
    kn: 'ಸರಾಸರಿ ಸ್ಕೋರ್',
    bn: 'গড় স্কোর',
    pa: 'ਔਸਤ ਅੰਕ',
    ml: 'ശരാശരി സ്കോർ',
    or: 'ହାରାହାରି ସ୍କୋର',
    ur: 'اوسط اسکور',
  },
  filterBy: {
    en: 'Filter By',
    hi: 'फिल्टर करें',
    gu: 'ફિલ્ટર',
    mr: 'फिल्टर',
    ta: 'வடிகட்டு',
    te: 'వడపోత',
    kn: 'ಫಿಲ್ಟರ್',
    bn: 'ফিল্টার',
    pa: 'ਫਿਲਟਰ',
    ml: 'അരിച്ചെടുക്കുക',
    or: 'ଫିଲ୍ଟର୍',
    ur: 'فلٹر',
  },
  course: {
    en: 'Course',
    hi: 'कोर्स',
    gu: 'કોર્સ',
    mr: 'अभ्यासक्रम',
    ta: 'பாடநெறி',
    te: 'కోర్సు',
    kn: 'ಕೋರ್ಸ್',
    bn: 'কোর্স',
    pa: 'ਕੋਰਸ',
    ml: 'കോഴ്സ്',
    or: 'ପାଠ୍ୟକ୍ରମ',
    ur: 'کورس',
  },
  semester: {
    en: 'Semester',
    hi: 'सत्र',
    gu: 'સત્ર',
    mr: 'सत्र',
    ta: 'செமஸ்டர்',
    te: 'సెమిస్టర్',
    kn: 'ಸೆಮಿಸ್ಟರ್',
    bn: 'সেমিস্টার',
    pa: 'ਸਮੈਸਟਰ',
    ml: 'സെമസ്റ്റർ',
    or: 'ସେମିଷ୍ଟର',
    ur: 'سمسٹر',
  },
  actions: {
    en: 'Actions',
    hi: 'क्रिया',
    gu: 'ક્રિયાઓ',
    mr: 'क्रिया',
    ta: 'செயல்கள்',
    te: 'చర్యలు',
    kn: 'ಕ್ರಿಯೆಗಳು',
    bn: 'ক্রিয়া',
    pa: 'ਕਾਰਵਾਈਆਂ',
    ml: 'പ്രവർത്തനങ്ങൾ',
    or: 'କାର୍ଯ୍ୟ',
    ur: 'اعمال',
  },
  aiInsight: {
    en: 'AI Insight',
    hi: 'एआई अंतर्दृष्टि',
    gu: 'AI સૂઝ',
    mr: 'AI अंतर्दृष्टी',
    ta: 'AI நுண்ணறிவு',
    te: 'AI అంతర్దృష్టి',
    kn: 'AI ಒಳನೋಟ',
    bn: 'AI অন্তর্দৃষ্টি',
    pa: 'AI ਜਾਣਕਾਰੀ',
    ml: 'AI ഉൾക്കാഴ്ച',
    or: 'AI ଅନ୍ତର୍ଦୃଷ୍ଟି',
    ur: 'اے آئی بصیرت',
  }
};

export const getTranslation = (key: string, lang: LanguageCode): string => {
  return TRANSLATIONS[key]?.[lang] || key;
};